RANDOM_SEED: 0

PHASE: "training"
EXPERIMENT_NAME: "overfit"
RESULTS_DIR: "results"
OVERFIT: True

SHAPENET_DATA:
    PATH: "/root/concert_meshes"

OPTIM:
    BATCH_SIZE: 2
    VAL_BATCH_SIZE: 4
    WORKERS: 8
    EPOCH: 100
    LR: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.005
    CLIP_GRADIENTS: 12.5

GCC:
    INPUT_MESH_FEATS: 3
    HIDDEN_DIMS: [128, 256, 512]
    CLASSES: 10
    CONV_INIT: "normal"
